---
- hosts: localhost
  tasks:
  - name: Create webapp CRD
    k8s:
      state: "{{ state | default('present') }}"
      definition:
        kind: WebApp
        apiVersion: app.example.com/v1alpha1
        metadata:
          name: test
          namespace: default
        spec:
          key: value
