---
- hosts: localhost
  tasks:
  - name: Create webapp CRs
    k8s:
      definition: "{{ lookup('template', 'webapp.template.yaml') | from_yaml }}"
    loop:
      - test
      - test-2
    loop_control:
      loop_var: name
