---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: default
  labels:
    app: memcached
spec:
  type: NodePort
  ports:
    - port: 11211
      nodePort: 30080
  selector:
    app: memcached
